name: Build Godot Project

on:
  push: {} # Runs on all Push
  pull_request: {} # Runs on all Pull-Request

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ChoukaBara-Windows, ChoukaBara-HTML5]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: ChoukaBara
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "./ChoukaBaraGame/"
          subdirectory: ${{ matrix.platform }}
          package: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }} - Artifact
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}