name: Build Godot Project

on:
  pull_request: {} # Runs on all Pull-Request

env:
  GODOT_VERSION: 3.2.3

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ChoukaBara-Windows, ChoukaBara-HTML5]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build ${{ matrix.platform }}
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: ChoukaBara
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "./ChoukaBaraGame/"
          subdirectory: ${{ matrix.platform }}
          package: true

      - name: Create Tar files
        run: tar -cvf ${{ matrix.platform }}.tgz ${{ github.workspace }}/${{ steps.build.outputs.build }}

      - name: Upload Artifact to Build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}.tgz
          path: ${{ matrix.platform }}.tgz

  Test:
    runs-on: ubuntu-latest
    needs: Godot
    container:
      image: barichello/godot-ci:3.2.3
    steps: 
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          apt-get install -y zip unzip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Run Tests
        run: |
          cd ./ChoukaBaraGame
          echo $(pwd)

          godot -v addons/WAT/cli.tscn -run_all

  Release:
    runs-on: ubuntu-latest
    needs: Test
    steps: 
      - name: Extract Change Logs
        id: extract-release-notes
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          filterByMilestone: true
          author: true
          unreleased: true # make false when releasing in future
            
      - name: Get Previous Release tag
        id: previous-tag
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft"
          view_top: 1

      - name: Format Tag Name
        id: formated-release-tag
        run: |
          echo ::set-output name=formated-tag::$(echo ${{ steps.previous-tag.outputs.tag_name }} | cut -d'v' -f 2)
        
      - name: Bump release version
        id: bump-version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.formated-release-tag.outputs.formated-tag }}
          version-fragment: 'bug' # Change here to Update release version in future Possible options are [ major | feature | bug | alpha | beta | rc ] version Format: major.feature.bug-alpha|beta|rc

      - name: Download HTML Build Artifacts
        id: downloaded-html-artifacts
        uses: actions/download-artifact@v2
        with:
          name: ChoukaBara-HTML5.tgz
          path: ~/artifacts/html

      - name: Download Windows Build Artifacts
        id: downloaded-windows-artifacts
        uses: actions/download-artifact@v2
        with:
          name: ChoukaBara-Windows.tgz
          path: ~/artifacts/windows

      - name: Create Pre-Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump-version.outputs.next-version }}
          release_name: Release ${{ steps.bump-version.outputs.next-version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: true # Change here to make prerelease as the actual release 

      - name: Upload Pre-Release Windows Asset
        id: upload-windows-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ${{ steps.downloaded-windows-artifacts.outputs.download-path }}/ChoukaBara-Windows.tgz
          asset_name: chouka-bara-windows.tgz
          asset_content_type: application/zip

      - name: Upload Pre-Release HTML5 Asset
        id: upload-html-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ${{ steps.downloaded-html-artifacts.outputs.download-path }}/ChoukaBara-HTML5.tgz
          asset_name: chouka-bara-html.tgz
          asset_content_type: application/zip