name: Build Godot Project

on:
  push: {} # Runs on all Push
  pull_request: {} # Runs on all Pull-Request

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ChoukaBara-Windows, ChoukaBara-HTML5]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: ChoukaBara
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "./ChoukaBaraGame/"
          subdirectory: ${{ matrix.platform }}
          package: "true"

      - name: Upload Artifact to Build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload Pre-Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_pre-release.outputs.upload_url }} 
          asset_path: ${{ steps.build.outputs.artifact }}
          asset_name: ${{ matrix.platform }}.zip
          asset_content_type: application/zip