# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build on Node ${{ matrix.os }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env: 
      working-directory: godotHtml

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Godot Export
      uses: firebelley/godot-export@v2.4.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_export_templates.tpz
        relative_project_path: ./ChoukaBaraGame/
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Build Directory
      run: |
        mkdir ${{ env.working-directory }}
        ls -ltr
        pwd
        ls -ltr "/home/runner/.local/share/godot/builds/ChoukaBara HTML5"
        cd "/home/runner/.local/share/godot/builds/ChoukaBara HTML5"
        cp -v * /home/runner/work/GodotGameChoukaBara/GodotGameChoukaBara/${{ env.working-directory }}
        cd -
        mv "${{ env.working-directory }}/ChoukaBara.html" "${{ env.working-directory }}/index.html"

    - name: Deploy Game HTML5 Site
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with: 
        target_branch: gh-pages
        build_dir: ${{ env.working-directory }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
